Repository celo-org/celo-blockchain, pull requests merged in 2019-12, with the labels that each got.

#677 retrieve validators and signers
  consensus/istanbul/backend/announce.go
  contract_comm/validators/validators.go
  ethstats/ethstats.go
Labels: automerge, betanet-blocker

#679 expose validator.signer address and warn on latency error
  contract_comm/validators/validators.go
  ethstats/ethstats.go
Labels: betanet-blocker

#684 Make bootnode image public
  cloudbuild-branchname.yaml
  cloudbuild.yaml
Labels: automerge

#694 Proxy SNBAT disconnect proxied validator from a max peers limit
  eth/handler.go
Labels: automerge

#697 Proxy SNBAT disconnect proxied validator from a max peers limit
  eth/handler.go
Labels: automerge

#692 Reduce intrinsic gas cost for txs paying fees in alternative currencies
  params/protocol_params.go
Labels: automerge

#702 Send gold to the reserve when rewarding validators with celo dollars
  consensus/istanbul/backend/pos.go
Labels: automerge

#733 Fix ethstats startup error
  consensus/istanbul/backend/backend.go
  ethstats/ethstats.go
Labels: betanet-phase-1

#746 Check that announced IP address is not an internal IP
  cmd/utils/flags.go
  consensus/istanbul/backend/engine.go
  consensus/istanbul/backend/handler.go
  consensus/istanbul/core/core.go
  consensus/istanbul/core/roundchange.go
  consensus/istanbul/errors.go
  eth/handler.go
  p2p/enode/urlv4.go
  p2p/enode/urlv4_test.go
Labels: betanet-phase-1

#745 Announce timestamp
  consensus/istanbul/backend/announce.go
  consensus/istanbul/backend/internal/enodes/val_enode_db.go
  consensus/istanbul/backend/internal/enodes/val_enode_db_test.go
  consensus/istanbul/backend/val_enodes_share.go
  consensus/istanbul/backend/val_enodes_share_test.go
Labels: automerge, betanet-phase-1

#748 getValEnodeTable RPC
  consensus/istanbul/backend/api.go
  consensus/istanbul/backend/internal/enodes/val_enode_db.go
  internal/web3ext/web3ext.go
Labels: automerge

#757 Make issue reporting better
  .github/ISSUE_TEMPLATE.md
  README.md
  cmd/geth/bugcmd.go
  cmd/geth/misccmd.go
Labels: automerge

#769 Add bootnodes to celo-node image
  Dockerfile.celo-node
Labels: automerge

#773 Add garbage collection for RoundStateDB
  common/task/task.go
  common/task/task_test.go
  consensus/istanbul/core/core.go
  consensus/istanbul/core/roundstate_db.go
  consensus/istanbul/core/roundstate_db_test.go
  consensus/istanbul/core/testutils_test.go
Labels: automerge, betanet-phase-2

#770 Loop until IBFT core catches up so that signatures can be added to block
  consensus/istanbul/backend/engine.go
  consensus/istanbul/core/core.go
  consensus/istanbul/core/handler.go
  consensus/istanbul/core/types.go
  eth/downloader/downloader.go
  miner/worker.go
  miner/worker_test.go
Labels: betanet-phase-2
