Repository celo-org/celo-blockchain, pull requests merged in 2019-11, with the labels that each got.

#562 Point CI back to master
  .circleci/config.yml
Labels: automerge

#572 Remove all identity-related code from celo-blockchain
  abe/abe.go
  cmd/geth/main.go
  cmd/geth/usage.go
  cmd/utils/flags.go
  core/state_processor.go
  core/types/receipt.go
  core/vm/contracts.go
  core/vm/evm.go
  core/vm/instructions.go
  eth/backend.go
  eth/config.go
  miner/miner.go
  miner/worker.go
  miner/worker_test.go
  params/protocol_params.go
Labels: automerge

#577 Update celo-node dockerfile to reflect what's on GCR
  Dockerfile.celo-node
Labels: automerge

#590 Panic on cache creation failure when creating a new backend for consensus
  consensus/istanbul/backend/backend.go
  consensus/istanbul/backend/engine.go
Labels: automerge

#608 Hide RoundState Implementation
  consensus/istanbul/core/backlog.go
  consensus/istanbul/core/commit.go
  consensus/istanbul/core/commit_test.go
  consensus/istanbul/core/core.go
  consensus/istanbul/core/errors.go
  consensus/istanbul/core/handler.go
  consensus/istanbul/core/message_set.go
  consensus/istanbul/core/message_set_test.go
  consensus/istanbul/core/prepare.go
  consensus/istanbul/core/prepare_test.go
  consensus/istanbul/core/request.go
  consensus/istanbul/core/request_test.go
  consensus/istanbul/core/roundchange.go
  consensus/istanbul/core/roundchange_test.go
  consensus/istanbul/core/roundstate.go
  consensus/istanbul/core/testbackend_test.go
  consensus/istanbul/core/testutils_test.go
  consensus/istanbul/core/types.go
Labels: automerge

#609 Remove unused code HasBadProposal
  .circleci/config.yml
  consensus/istanbul/backend.go
  consensus/istanbul/backend/backend.go
  consensus/istanbul/core/backlog_test.go
  consensus/istanbul/core/core.go
  consensus/istanbul/core/request_test.go
  consensus/istanbul/core/roundstate.go
  consensus/istanbul/core/testbackend_test.go
  consensus/istanbul/core/testutils_test.go
Labels: automerge

#610 Cleanup MessageSet
  consensus/istanbul/core/message_set.go
Labels: automerge

#611 Manual revert #520 "Persist Proposer state across restarts"
  consensus/istanbul/backend.go
  consensus/istanbul/backend/backend.go
  consensus/istanbul/backend/backend_test.go
  consensus/istanbul/backend/engine_test.go
  consensus/istanbul/backend/snapshot_test.go
  consensus/istanbul/core/core.go
  consensus/istanbul/core/persistent_state.go
  consensus/istanbul/core/preprepare.go
  consensus/istanbul/core/testbackend_test.go
  eth/backend.go
  miner/worker_test.go
Labels: automerge

#612 Cleanup: newLogger & remove core.View()
  consensus/istanbul/core/backlog.go
  consensus/istanbul/core/backlog_test.go
  consensus/istanbul/core/commit.go
  consensus/istanbul/core/core.go
  consensus/istanbul/core/handler.go
  consensus/istanbul/core/prepare.go
  consensus/istanbul/core/preprepare.go
  consensus/istanbul/core/preprepare_test.go
  consensus/istanbul/core/request.go
  consensus/istanbul/core/roundchange.go
  consensus/istanbul/core/roundchange_test.go
  consensus/istanbul/core/roundstate.go
Labels: automerge

#603 Fix check for whether or not an existing ValEnodeTable entry has changed
  consensus/istanbul/backend/announce.go
  consensus/istanbul/backend/backend.go
  consensus/istanbul/backend/internal/enodes/val_enode_db.go
  consensus/istanbul/core/core.go
  consensus/istanbul/core/prepare.go
  consensus/istanbul/core/preprepare.go
  core/state_transition.go
Labels: automerge

#604 Verify IBFT preprepare proposal block number matches sequence number
  consensus/istanbul/core/preprepare.go
  consensus/istanbul/core/preprepare_test.go
Labels: automerge

#584 Extra receipt for internal EVM call when finalizing blocks
  consensus/istanbul/backend/engine.go
  core/blockchain.go
  core/state_processor.go
  miner/worker.go
Labels: automerge

#624 Fix for backlogging of commit messages
  consensus/istanbul/core/backlog.go
  consensus/istanbul/core/backlog_test.go
Labels: automerge

#602 Replace GasFeeRecipient with GatewayFee
  .circleci/config.yml
  accounts/abi/bind/backends/simulated.go
  accounts/abi/bind/base.go
  accounts/abi/bind/util_test.go
  cmd/faucet/faucet.go
  cmd/utils/flags.go
  contract_comm/blockchain_parameters/blockchain_parameters.go
  contract_comm/currency/currency.go
  contract_comm/evm.go
  core/bench_test.go
  core/blockchain_test.go
  core/chain_makers_test.go
  core/rawdb/accessors_indexes_test.go
  core/state_transition.go
  core/tx_list.go
  core/tx_pool.go
  core/tx_pool_test.go
  core/types/block_test.go
  core/types/transaction.go
  core/types/transaction_signing.go
  core/types/transaction_signing_test.go
  core/types/transaction_test.go
  eth/api_backend.go
  eth/backend.go
  eth/config.go
  eth/downloader/testchain_test.go
  eth/fetcher/fetcher_test.go
  eth/filters/filter_system_test.go
  eth/handler_test.go
  eth/helper_test.go
  eth/tracers/tracers_test.go
  interfaces.go
  internal/ethapi/api.go
  internal/ethapi/backend.go
  les/api_backend.go
  les/backend.go
  les/handler.go
  les/handler_test.go
  les/helper_test.go
  les/odr_test.go
  les/server.go
  les/txrelay.go
  light/odr_test.go
  light/txpool.go
  light/txpool_test.go
  miner/worker.go
  miner/worker_test.go
  mobile/types.go
  params/protocol_params.go
  signer/core/types.go
  signer/rules/rules_test.go
  tests/state_test_util.go
Labels: betanet-blocker

#618 Track uptime & distribute rewards based on it
  .circleci/config.yml
  cmd/geth/main.go
  cmd/geth/usage.go
  cmd/utils/flags.go
  consensus/istanbul/backend/engine.go
  consensus/istanbul/backend/engine_test.go
  consensus/istanbul/backend/pos.go
  consensus/istanbul/config.go
  consensus/istanbul/types.go
  consensus/istanbul/utils.go
  core/blockchain.go
  core/blockchain_test.go
  core/rawdb/accessors_chain.go
  core/rawdb/accessors_chain_test.go
  core/rawdb/schema.go
  eth/backend.go
  params/config.go
  params/protocol_params.go
Labels: betanet-blocker

#622 Ethstats with proxy and proxied validator (client)
  consensus/istanbul/backend/backend.go
  consensus/istanbul/backend/handler.go
  ethstats/ethstats.go
Labels: betanet-blocker

#639 Always run the election after block finalization
  core/types/block.go
  miner/worker.go
Labels: automerge

#640 Separate public key and signature in proof-of-possession command
  accounts/accounts.go
  accounts/keystore/keystore.go
  accounts/keystore/wallet.go
  accounts/usbwallet/wallet.go
  cmd/geth/accountcmd.go
Labels: betanet-blocker

#642 Update celo-node dockerfile for baklava
  Dockerfile.celo-node
Labels: automerge

#656 Update account proof-of-possession command to work with BLS and ECDSA
  accounts/accounts.go
  accounts/keystore/keystore.go
  accounts/keystore/wallet.go
  accounts/usbwallet/wallet.go
  cmd/geth/accountcmd.go
Labels: automerge

#653 Ensure ScoreTally gets calculated correctly
  consensus/istanbul/backend/pos.go
  consensus/istanbul/types.go
  core/blockchain.go
  core/blockchain_test.go
  core/rawdb/accessors_chain.go
  core/rawdb/accessors_chain_test.go
Labels: automerge, betanet-blocker

#616 Remove the set-node-key command
  accounts/keystore/keystore.go
  cmd/geth/accountcmd.go
Labels: do not merge

#660 Fix iOS podspec to include bls snark lib
  CeloBlockchain.podspec
  package.json
Labels: automerge

#665 create validator connections on upsert
  consensus/istanbul/backend/internal/enodes/val_enode_db.go
Labels: automerge

#667 Fix non-fatal panic on forwarding transactions without gateway fee
  les/peer.go
  les/txrelay.go
  light/txpool.go
  light/txpool_test.go
Labels: automerge

#663 Make celo-node Dockerfile a little less error-prone
  Dockerfile.celo-node
Labels: automerge

#669 Only reward voters for each group that elected validators once
  consensus/istanbul/backend/pos.go
  contract_comm/election/election.go
Labels: automerge

#671 Don't reuse variable i in pos.go
  contract_comm/election/election.go
Labels: betanet-blocker

#674 Sort validator group votes in descending order
  accounts/keystore/keystore.go
  cmd/geth/accountcmd.go
  contract_comm/election/election.go
Labels: automerge, betanet-blocker
