Repository celo-org/celo-blockchain, pull requests merged in 2021-02, with the labels that each got.

#1338 Add Churrito and Donut override flags
  cmd/geth/config.go
  cmd/geth/main.go
  cmd/utils/flags.go
  core/genesis.go
  eth/backend.go
  eth/config.go
  eth/gen_config.go
  les/client.go
Labels: donut

#1249 CIP-20: Extensible Hash Functions
  core/vm/cip20.go
  core/vm/contracts.go
  core/vm/contracts_test.go
  core/vm/testdata/precompiles/cip20.json
  crypto/blake2s/README
  crypto/blake2s/blake2s.go
  crypto/blake2s/blake2s_test.go
  crypto/blake2s/block.go
  go.sum
  params/protocol_params.go
Labels: donut

#1340 Prestwich+kilic/bls12381
  core/vm/contracts.go
  core/vm/contracts_test.go
  core/vm/testdata/precompiles/blsG1Add.json
  core/vm/testdata/precompiles/blsG1Mul.json
  core/vm/testdata/precompiles/blsG1MultiExp.json
  core/vm/testdata/precompiles/blsG2Add.json
  core/vm/testdata/precompiles/blsG2Mul.json
  core/vm/testdata/precompiles/blsG2MultiExp.json
  core/vm/testdata/precompiles/blsMapG1.json
  core/vm/testdata/precompiles/blsMapG2.json
  core/vm/testdata/precompiles/blsPairing.json
  core/vm/testdata/precompiles/fail-blsG1Add.json
  core/vm/testdata/precompiles/fail-blsG1Mul.json
  core/vm/testdata/precompiles/fail-blsG1MultiExp.json
  core/vm/testdata/precompiles/fail-blsG2Add.json
  core/vm/testdata/precompiles/fail-blsG2Mul.json
  core/vm/testdata/precompiles/fail-blsG2MultiExp.json
  core/vm/testdata/precompiles/fail-blsMapG1.json
  core/vm/testdata/precompiles/fail-blsMapG2.json
  core/vm/testdata/precompiles/fail-blsPairing.json
  crypto/bls12381/arithmetic_decl.go
  crypto/bls12381/arithmetic_fallback.go
  crypto/bls12381/arithmetic_x86.s
  crypto/bls12381/bls12_381.go
  crypto/bls12381/bls12_381_test.go
  crypto/bls12381/field_element.go
  crypto/bls12381/field_element_test.go
  crypto/bls12381/fp.go
  crypto/bls12381/fp12.go
  crypto/bls12381/fp2.go
  crypto/bls12381/fp6.go
  crypto/bls12381/fp_fallback.go
  crypto/bls12381/fp_test.go
  crypto/bls12381/g1.go
  crypto/bls12381/g1_test.go
  crypto/bls12381/g2.go
  crypto/bls12381/g2_test.go
  crypto/bls12381/glv.go
  crypto/bls12381/glv_test.go
  crypto/bls12381/gt.go
  crypto/bls12381/hash_to_field.go
  crypto/bls12381/isogeny.go
  crypto/bls12381/pairing.go
  crypto/bls12381/pairing_test.go
  crypto/bls12381/swu.go
  crypto/bls12381/utils.go
  crypto/bls12381/wnaf.go
  crypto/bls12381/wnaf_test.go
  go.mod
  go.sum
  params/protocol_params.go
  patches/mobileLibsForBuild.patch
Labels: donut

#1349 Adds script to build and publish a private docker image
  scripts/publish_private_docker_image.sh
Labels: automerge

#1385 Small fixes for mycelo validator-run command.
  mycelo/cluster/node.go
Labels: blockchain

#1154 Add metric: blockFinalizationTime
  miner/worker.go
Labels: automerge

#1404 [mycelo] typos on env accounts cmd
  cmd/mycelo/env_commands.go
  mycelo/env/accounts.go
Labels: automerge

#1403 Update Readme with rename tooling
  README.md
Labels: automerge
