Repository celo-org/celo-blockchain, pull requests merged in 2021-06, with the labels that each got.

#1565 Remove support for celo/64 and celo/65 protocols.
  consensus/istanbul/protocol.go
  eth/handler.go
  p2p/peer.go
  p2p/protocol.go
  p2p/server.go
Labels: theme: housekeeping

#1567 Clean up mycelo genesis config type overrides
  mycelo/genesis/config.go
Labels: tech-debt

#1606 Piersy/update prepare-system-contracts make rule
  Makefile
  README.md
  scripts/check_imports.sh
  scripts/hooks/pre-commit
  scripts/rename_imports.sh
Labels: blockchain, current-sprint

#1597 Move several sign&address properties from istanbul.Backend to its own type
  consensus/istanbul/backend/announce.go
  consensus/istanbul/backend/backend.go
  consensus/istanbul/backend/engine.go
  consensus/istanbul/backend/handler_test.go
  consensus/istanbul/backend/random.go
  consensus/istanbul/backend/test_utils.go
Labels: automerge
