Repository celo-org/celo-blockchain, pull requests merged in 2021-03, with the labels that each got.

#1411 [Housekeeping] Remove go-bip39 from the node
  accounts/scwallet/README.md
  accounts/scwallet/apdu.go
  accounts/scwallet/hub.go
  accounts/scwallet/securechannel.go
  accounts/scwallet/wallet.go
  console/bridge.go
  internal/ethapi/api.go
  node/config.go
  signer/core/api.go
Labels: automerge

#1406 Adds flag to limit pending txs
  cmd/mycelo/main.go
  mycelo/loadbot/bot.go
Labels: automerge

#1413 Change verbose info log
  consensus/istanbul/proxy/proxied_validator_engine.go
Labels: automerge

#1416 Update mycelo to work with e2e tests in celo-monorepo
  cmd/mycelo/README.md
  cmd/mycelo/genesis_commands.go
  cmd/mycelo/templates.go
  common/decimal/bigintstr/big_int_str.go
  mycelo/env/types.go
  mycelo/genesis/base_config.go
  mycelo/genesis/config.go
  mycelo/genesis/gen_balance_json.go
  mycelo/genesis/gen_double_signing_slasher_parameters_json.go
  mycelo/genesis/gen_downtime_slasher_parameters_json.go
  mycelo/genesis/gen_election_parameters_json.go
  mycelo/genesis/gen_epoch_rewards_parameters_json.go
  mycelo/genesis/gen_gas_price_minimum_parameters_json.go
  mycelo/genesis/gen_governance_parameters_json.go
  mycelo/genesis/gen_locked_gold_requirements_json.go
  mycelo/genesis/gen_reserve_parameters_json.go
  mycelo/genesis/genesis_state.go
Labels: theme: dev-productivity

#1421 Adds passthrough flag to mycelo
  cmd/mycelo/genesis_commands.go
  cmd/mycelo/main.go
  mycelo/cluster/cluster.go
  mycelo/cluster/node.go
Labels: automerge

#1412 Remove Ethereum flags that don't apply to Celo
  cmd/clef/README.md
  cmd/clef/main.go
  cmd/geth/chaincmd.go
  cmd/geth/main.go
  cmd/geth/usage.go
  cmd/utils/flags.go
  core/chain_makers.go
  docs/docs/_interface/Command-Line-Options.md
  node/config.go
  signer/core/api.go
  signer/core/api_test.go
Labels: automerge

#1414 Message Handler Benchmarking
  consensus/istanbul/core/commit_test.go
  consensus/istanbul/core/handler_test.go
  consensus/istanbul/core/prepare_test.go
Labels: automerge

#1436 Fix unit tests
  consensus/istanbul/core/commit.go
  consensus/istanbul/core/commit_test.go
Labels: automerge

#1431 Implement CIP35 for Donut hard fork
  accounts/abi/bind/backends/simulated.go
  cmd/geth/retesteth_copypaste.go
  contract_comm/evm.go
  core/error.go
  core/state_processor.go
  core/state_transition.go
  core/tx_pool.go
  core/tx_pool_test.go
  core/types/gen_tx_json.go
  core/types/transaction.go
  core/types/transaction_signing.go
  core/types/transaction_test.go
  core/vm/context.go
  core/vm/contracts_test.go
  interfaces.go
  internal/ethapi/api.go
  les/odr_test.go
  light/odr_test.go
  light/txpool.go
  rlp/decode.go
  rlp/decode_test.go
  rpc/types.go
  signer/core/types.go
  signer/fourbyte/validation.go
  tests/state_test_util.go
Labels: donut

#1472 Set Baklava Donut activation (block 5002000, April 13, 2021)
  params/config.go
Labels: donut
