Repository celo-org/celo-blockchain, pull requests merged in 2021-07, with the labels that each got.

#1590 Announce protocol code refactor
  consensus/istanbul/backend/announce.go
  consensus/istanbul/backend/announce_test.go
  consensus/istanbul/backend/api.go
  consensus/istanbul/backend/backend.go
  consensus/istanbul/backend/handler.go
  consensus/istanbul/backend/version_certificate.go
Labels: automerge

#1561 updated readme.md to include geth http params
  README.md
Labels: automerge

#1614 Update gitignore
  .gitignore
Labels: automerge

#1592 Consolidate istanbul.Message encoding/decoding
  consensus/istanbul/backend/announce.go
  consensus/istanbul/backend/announce_test.go
  consensus/istanbul/backend/internal/enodes/version_certificate_db.go
  consensus/istanbul/backend/internal/enodes/version_certificate_db_test.go
  consensus/istanbul/backend/version_certificate.go
  consensus/istanbul/core/backlog.go
  consensus/istanbul/core/backlog_test.go
  consensus/istanbul/core/commit.go
  consensus/istanbul/core/commit_test.go
  consensus/istanbul/core/core.go
  consensus/istanbul/core/errors.go
  consensus/istanbul/core/handler_test.go
  consensus/istanbul/core/prepare.go
  consensus/istanbul/core/prepare_test.go
  consensus/istanbul/core/preprepare.go
  consensus/istanbul/core/preprepare_test.go
  consensus/istanbul/core/roundchange.go
  consensus/istanbul/core/roundchange_test.go
  consensus/istanbul/core/testbackend_test.go
  consensus/istanbul/core/types_test.go
  consensus/istanbul/proxy/forward_message.go
  consensus/istanbul/proxy/proxy_engine_test.go
  consensus/istanbul/proxy/types.go
  consensus/istanbul/proxy/val_enodes_share.go
  consensus/istanbul/types.go
  consensus/istanbul/types_test.go
Labels: blockchain, current-sprint

#1622 Fix VersionCertificate rlp encoding/decoding
  consensus/istanbul/backend/internal/enodes/version_certificate_db.go
  consensus/istanbul/types.go
Labels: blockchain, bug, current-sprint

#1629 fix: Registry code size check
  core/genesis.go
  core/genesis_test.go
  params/protocol_params.go
Labels: blockchain
